# Generated by Django 5.0.7 on 2025-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_bio_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'sent'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], max_length=9),
        ),
    ]
