# Generated by Django 5.0.7 on 2025-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
