# Generated by Django 5.0.7 on 2025-02-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_github_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buy_me_coffee',
            field=models.URLField(blank=True, help_text='Your Buy Me a Coffee profile link', null=True, verbose_name='Buy Me a Coffee Link'),
        ),
    ]
