# Generated by Django 5.0.7 on 2025-02-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('output_file', models.FileField(null=True, upload_to='converted/')),
                ('input_format', models.CharField(max_length=10)),
                ('output_format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
