# Generated by Django 5.0.7 on 2025-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
