# Generated by Django 5.0.7 on 2025-02-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_joinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
