# Generated by Django 5.0.7 on 2025-01-30 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_document_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postvideo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='document',
            field=models.FileField(upload_to='post_documents/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post_videos/'),
        ),
    ]
