# Generated by Django 5.0.7 on 2025-02-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='comment_videos/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='comment_voice/'),
        ),
    ]
