# Generated by Django 5.0.7 on 2025-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_usercontribution_total_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontribution',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
